platform :ios, '8.0'
inhibit_all_warnings!

target 'CAlert_Example' do
  use_frameworks!
  pod 'ZWAlertController', :path => '../'
  
  target 'CAlert_Tests' do
    inherit! :search_paths

    
  end
end
